# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\authDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(329, 148)
        self.gridLayout = QtWidgets.QGridLayout(Login)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButtonOK = QtWidgets.QPushButton(Login)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout.addWidget(self.pushButtonOK, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Login)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.gridLayout.addWidget(self.pushButtonAbbrechen, 3, 1, 1, 1)
        self.lineEditPW = QtWidgets.QLineEdit(Login)
        self.lineEditPW.setObjectName("lineEditPW")
        self.gridLayout.addWidget(self.lineEditPW, 2, 0, 1, 2)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Passwort:"))
        self.pushButtonOK.setText(_translate("Login", "OK"))
        self.label.setText(_translate("Login", "Administrator-Login"))
        self.pushButtonAbbrechen.setText(_translate("Login", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
