# Form implementation generated from reading ui file '.\codeabruf.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CodeAbrufen(object):
    def setupUi(self, CodeAbrufen):
        CodeAbrufen.setObjectName("CodeAbrufen")
        CodeAbrufen.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\images/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CodeAbrufen.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(CodeAbrufen)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(CodeAbrufen)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBoxLaufzeit = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLaufzeit.sizePolicy().hasHeightForWidth())
        self.comboBoxLaufzeit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.comboBoxLaufzeit.setFont(font)
        self.comboBoxLaufzeit.setObjectName("comboBoxLaufzeit")
        self.horizontalLayout.addWidget(self.comboBoxLaufzeit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonOK = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.pushButtonAbbrechen.setFont(font)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.horizontalLayout_2.addWidget(self.pushButtonAbbrechen)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(CodeAbrufen)
        QtCore.QMetaObject.connectSlotsByName(CodeAbrufen)

    def retranslateUi(self, CodeAbrufen):
        _translate = QtCore.QCoreApplication.translate
        CodeAbrufen.setWindowTitle(_translate("CodeAbrufen", "Code abrufen"))
        self.groupBox.setTitle(_translate("CodeAbrufen", "WLAN Code abrufen"))
        self.label_5.setText(_translate("CodeAbrufen", "<html><head/><body><p>Schüler*innen erhalten in der Regel einen Code mit 1 Stunde Laufzeit.</p><p>Die Laufzeit der Codes beginnt mit der ersten Verbindung eines Gerätes mit dem WLAN.</p></body></html>"))
        self.label_6.setText(_translate("CodeAbrufen", "Laufzeit: "))
        self.comboBoxLaufzeit.setPlaceholderText(_translate("CodeAbrufen", "Bitte wählen"))
        self.pushButtonOK.setText(_translate("CodeAbrufen", "Code abrufen"))
        self.pushButtonAbbrechen.setText(_translate("CodeAbrufen", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CodeAbrufen = QtWidgets.QWidget()
    ui = Ui_CodeAbrufen()
    ui.setupUi(CodeAbrufen)
    CodeAbrufen.show()
    sys.exit(app.exec())
