# Form implementation generated from reading ui file '.\ui\firstpasswd.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswortEinrichtung(object):
    def setupUi(self, PasswortEinrichtung):
        PasswortEinrichtung.setObjectName("PasswortEinrichtung")
        PasswortEinrichtung.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PasswortEinrichtung.resize(276, 184)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../images/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PasswortEinrichtung.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(PasswortEinrichtung)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonOK = QtWidgets.QPushButton(PasswortEinrichtung)
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout.addWidget(self.pushButtonOK, 0, 0, 1, 1)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(PasswortEinrichtung)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.gridLayout.addWidget(self.pushButtonAbbrechen, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(PasswortEinrichtung)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(PasswortEinrichtung)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEditNeuPW = QtWidgets.QLineEdit(PasswortEinrichtung)
        self.lineEditNeuPW.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditNeuPW.setClearButtonEnabled(True)
        self.lineEditNeuPW.setObjectName("lineEditNeuPW")
        self.gridLayout_2.addWidget(self.lineEditNeuPW, 2, 0, 1, 1)
        self.lineEditWdhNeuPW = QtWidgets.QLineEdit(PasswortEinrichtung)
        self.lineEditWdhNeuPW.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditWdhNeuPW.setClearButtonEnabled(True)
        self.lineEditWdhNeuPW.setObjectName("lineEditWdhNeuPW")
        self.gridLayout_2.addWidget(self.lineEditWdhNeuPW, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(PasswortEinrichtung)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)

        self.retranslateUi(PasswortEinrichtung)
        QtCore.QMetaObject.connectSlotsByName(PasswortEinrichtung)
        PasswortEinrichtung.setTabOrder(self.lineEditNeuPW, self.lineEditWdhNeuPW)
        PasswortEinrichtung.setTabOrder(self.lineEditWdhNeuPW, self.pushButtonOK)
        PasswortEinrichtung.setTabOrder(self.pushButtonOK, self.pushButtonAbbrechen)

    def retranslateUi(self, PasswortEinrichtung):
        _translate = QtCore.QCoreApplication.translate
        PasswortEinrichtung.setWindowTitle(_translate("PasswortEinrichtung", "Passwort einrichten"))
        self.pushButtonOK.setText(_translate("PasswortEinrichtung", "OK"))
        self.pushButtonAbbrechen.setText(_translate("PasswortEinrichtung", "Abbrechen"))
        self.label.setText(_translate("PasswortEinrichtung", "Festlegen eines Administrator-Passworts"))
        self.label_3.setText(_translate("PasswortEinrichtung", "Passwort:"))
        self.label_4.setText(_translate("PasswortEinrichtung", "Wiederholung Passwort:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswortEinrichtung = QtWidgets.QDialog()
    ui = Ui_PasswortEinrichtung()
    ui.setupUi(PasswortEinrichtung)
    PasswortEinrichtung.show()
    sys.exit(app.exec())
