# Form implementation generated from reading ui file '.\fullscreen.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Fullscreen(object):
    def setupUi(self, Fullscreen):
        Fullscreen.setObjectName("Fullscreen")
        Fullscreen.resize(1024, 409)
        self.gridLayout = QtWidgets.QGridLayout(Fullscreen)
        self.gridLayout.setObjectName("gridLayout")
        self.labelCode = QtWidgets.QLabel(Fullscreen)
        font = QtGui.QFont()
        font.setPointSize(96)
        font.setBold(True)
        font.setWeight(75)
        self.labelCode.setFont(font)
        self.labelCode.setStyleSheet("background-color: rgb(226, 240, 255);")
        self.labelCode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCode.setObjectName("labelCode")
        self.gridLayout.addWidget(self.labelCode, 0, 0, 1, 1)
        self.pushButtonClose = QtWidgets.QPushButton(Fullscreen)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout.addWidget(self.pushButtonClose, 1, 0, 1, 1)

        self.retranslateUi(Fullscreen)
        QtCore.QMetaObject.connectSlotsByName(Fullscreen)

    def retranslateUi(self, Fullscreen):
        _translate = QtCore.QCoreApplication.translate
        Fullscreen.setWindowTitle(_translate("Fullscreen", "Form"))
        self.labelCode.setText(_translate("Fullscreen", "00000-00000"))
        self.pushButtonClose.setText(_translate("Fullscreen", "Schließen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fullscreen = QtWidgets.QWidget()
    ui = Ui_Fullscreen()
    ui.setupUi(Fullscreen)
    Fullscreen.show()
    sys.exit(app.exec())
