# Form implementation generated from reading ui file '.\importWindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportWindow(object):
    def setupUi(self, ImportWindow):
        ImportWindow.setObjectName("ImportWindow")
        ImportWindow.resize(437, 139)
        self.gridLayout_3 = QtWidgets.QGridLayout(ImportWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(ImportWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ImportWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ButtonDateiname = QtWidgets.QPushButton(ImportWindow)
        self.ButtonDateiname.setMaximumSize(QtCore.QSize(31, 23))
        self.ButtonDateiname.setObjectName("ButtonDateiname")
        self.gridLayout.addWidget(self.ButtonDateiname, 0, 2, 1, 1)
        self.lineEditDateiname = QtWidgets.QLineEdit(ImportWindow)
        self.lineEditDateiname.setMinimumSize(QtCore.QSize(291, 20))
        self.lineEditDateiname.setObjectName("lineEditDateiname")
        self.gridLayout.addWidget(self.lineEditDateiname, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(ImportWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBoxRuntime = QtWidgets.QSpinBox(ImportWindow)
        self.spinBoxRuntime.setMaximumSize(QtCore.QSize(41, 20))
        self.spinBoxRuntime.setProperty("value", 1)
        self.spinBoxRuntime.setObjectName("spinBoxRuntime")
        self.gridLayout_2.addWidget(self.spinBoxRuntime, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ImportWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonImport = QtWidgets.QPushButton(ImportWindow)
        self.ButtonImport.setObjectName("ButtonImport")
        self.horizontalLayout.addWidget(self.ButtonImport)
        self.ButtonClose = QtWidgets.QPushButton(ImportWindow)
        self.ButtonClose.setObjectName("ButtonClose")
        self.horizontalLayout.addWidget(self.ButtonClose)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 1, 1, 1)

        self.retranslateUi(ImportWindow)
        QtCore.QMetaObject.connectSlotsByName(ImportWindow)

    def retranslateUi(self, ImportWindow):
        _translate = QtCore.QCoreApplication.translate
        ImportWindow.setWindowTitle(_translate("ImportWindow", "Code-Import"))
        self.label_2.setText(_translate("ImportWindow", "Codes importieren (Textdatei mit einem Code pro Zeile)"))
        self.label.setText(_translate("ImportWindow", "Dateiname:"))
        self.ButtonDateiname.setText(_translate("ImportWindow", "..."))
        self.label_3.setText(_translate("ImportWindow", "Eingestellte Laufzeit der Codes:"))
        self.label_4.setText(_translate("ImportWindow", "Stunde"))
        self.ButtonImport.setText(_translate("ImportWindow", "Import"))
        self.ButtonClose.setText(_translate("ImportWindow", "Schließen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportWindow = QtWidgets.QWidget()
    ui = Ui_ImportWindow()
    ui.setupUi(ImportWindow)
    ImportWindow.show()
    sys.exit(app.exec())
